<?php
/**
 * @file
 * Code for the EF Events feature.
 */

include_once 'ef_events.features.inc';

/**
 * Implements hook_node_info().
 */
function ef_events_node_info() {
  $items = array(
    'event_payable' => array(
      'name' => t('Paid Event'),
      'base' => 'node_content',
      'description' => t('Post information about planned activities or meetings, which can be purchased.'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  return $items;
}

/**
 * Implements hook_form_alter().
 */
function ef_events_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'event_payable_node_form') {
    //$form['actions']['submit']['#submit'][] = '_ef_events_paid_event_redirect';
  }
}

function _ef_events_paid_event_redirect($form, &$form_state) {
  // No longer needed since decoupled from Registration, but keeping just in
  /// case we can reuse this.
  //$form_state['redirect'] = 'node/' . $form_state['node']->nid . '/registrations/settings';
}